development:
  adapter: postgresql
  encoding: unicode
  database: gavinblog_development
  pool: 5
  timeout: 5000
  username: gching

test:
  adapter: postgresql
  encoding: unicode
  database: gavinblog_test
  pool: 5
  timeout: 5000
  username: gching